### ISSUE TITLE
Stylus-loader error

### ISSUE THREAD

**Issue by biloup** [vuetifyjs/webpack-advanced#14]
After installing the packages, when I run the application in dev mode I have an error that I don't understand.

```
$ npm run dev

> security_quiz@1.0.0 dev /home/clem/Documents/test/Project_name
> node build/dev-server.js

> Starting dev server...


 ERROR  Failed to compile with 1 errors                                                                                                                         13:32:32

 error  in ./src/App.vue

Module build failed: Error: /home/clem/Documents/test/Project_name/src/App.vue:118:24
   114|   }
   115| </script>
   116| 
   117| <style lang="stylus">
   118|   @import './stylus/main'
-------------------------------^
   119| </style>
   120| 

failed to locate @import file /home/clem/Documents/test/Project_name/node_modules/stylus/lib/functions.styl

    at CachedPathEvaluator.visitImport (/home/clem/Documents/test/Project_name/node_modules/stylus-loader/lib/evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/home/clem/Documents/test/Project_name/node_modules/stylus/lib/renderer.js:86:26)
    at /home/clem/Documents/test/Project_name/node_modules/stylus-loader/index.js:165:12
    at tryCatchReject (/home/clem/Documents/test/Project_name/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/home/clem/Documents/test/Project_name/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/home/clem/Documents/test/Project_name/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/home/clem/Documents/test/Project_name/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/home/clem/Documents/test/Project_name/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/clem/Documents/test/Project_name/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":false,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-6a9e8c0a","scoped":false,"hasInlineConfig":false}!./node_modules/stylus-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-377 13:3-17:5 14:22-385
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080
```

**Comment by maurop123** [comment]
Thanks for reporting this. Figured out that it started because of a change in the most recent pull request, which has now been reverted. Just tested and it seems to work. Let us know if you see it working now.

**Comment by biloup** [comment]
The error is staying after retrying.

**Comment by maurop123** [comment]
Did you run `vue init vuetifyjs/webpack-advanced` again?

I just made another change, unrelated to this issue, but now you should definitely get the new version of the template.

**Comment by biloup** [comment]
I have still the same error.
`vue init vuetifyjs/webpack-advanced my-project`
```
? Project name my-project
? Project description A Vue.js project
? Author biloup07 <clemb07430@gmail.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Setup unit tests with Karma + Mocha? Yes
? Setup e2e tests with Nightwatch? Yes

   vue-cli · Generated "my-project".

   To get started:
   
     cd my-project
     npm install
     npm run dev
   
   Documentation can be found at https://vuejs-templates.github.io/webpack


```
`npm install`
```
> phantomjs-prebuilt@2.1.15 install /home/clem/Documents/test/my-project/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
Writing location.js file
PhantomJS is already installed on PATH at /usr/bin/phantomjs

> chromedriver@2.32.2 install /home/clem/Documents/test/my-project/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1566K...
Received 2350K...
Received 3134K...
Received 3918K...
Received 3978K total.
Extracting zip contents
Copying to target path /home/clem/Documents/test/my-project/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/clem/Documents/test/my-project/node_modules/chromedriver/lib/chromedriver/chromedriver
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1311 packages in 55.909s

```

`npm run dev`
```

> my-project@1.0.0 dev /home/clem/Documents/test/my-project
> node build/dev-server.js

> Starting dev server...


 ERROR  Failed to compile with 1 errors                                                                                                                         10:09:42

 error  in ./src/stylus/main.styl

Module build failed: Error: /home/clem/Documents/test/my-project/src/stylus/main.styl:2:9
   1| /** Stylus Styles */
   2| @import '../../node_modules/vuetify/src/stylus/main'
--------------^

failed to locate @import file /home/clem/Documents/test/my-project/node_modules/stylus/lib/functions.styl

    at CachedPathEvaluator.visitImport (/home/clem/Documents/test/my-project/node_modules/stylus-loader/lib/evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (/home/clem/Documents/test/my-project/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/home/clem/Documents/test/my-project/node_modules/stylus/lib/renderer.js:86:26)
    at /home/clem/Documents/test/my-project/node_modules/stylus-loader/index.js:165:12
    at tryCatchReject (/home/clem/Documents/test/my-project/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/home/clem/Documents/test/my-project/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/home/clem/Documents/test/my-project/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/home/clem/Documents/test/my-project/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/home/clem/Documents/test/my-project/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/clem/Documents/test/my-project/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./src/stylus/main.styl 4:14-141 13:3-17:5 14:22-149
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080
```

**Comment by maurop123** [comment]
This is a tough one. I can't reproduce it.

What is your vue cli version (`vue -V`)? Mine is 2.8.2

**Comment by biloup** [comment]
```
$ vue -V
2.8.2
```

**Comment by maurop123** [comment]
It's been a while since this was opened and there's been a lot of changes. Are you still having the same issue when making a new project @biloup ?

**Comment by maurop123** [comment]
Gonna close this issue now. If you still need help getting your project to run, you can jump on the discord chat here: https://discordapp.com/channels/340160225338195969/340215499398840331
