### ISSUE TITLE
Module build failed: Error: Cannot find module './lib/beautify'

### ISSUE THREAD

**Issue by pzdz** [vuetifyjs/webpack-advanced#17]
I came across the error below when trying to update dependencies of my current project. It happens also for newly created project based on this template.

```
Module build failed: Error: Cannot find module './lib/beautify'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/pawel/Code/Playground/vuetify-webpack-advanced/node_modules/js-beautify/js/index.js:74:27
    at Object.<anonymous> (/Users/pawel/Code/Playground/vuetify-webpack-advanced/node_modules/js-beautify/js/index.js:80:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pawel/Code/Playground/vuetify-webpack-advanced/node_modules/vue-loader/lib/template-compiler/index.js:4:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

beautify-web/js-beautify just hit 1.7.0 and there is no lib/beautify.js anymore, just lib/index.js. This is vue-loader issue (https://github.com/vuejs/vue-loader/issues/983) and the workaround is to downgrade js-beutify
```
npm install js-beautify@1.6.14
```
This is not a vuetifyjs/webpack-advanced issue per se, but I can imagine people may be confused when a newly created project will fail to run.

--- EDITED 

But the above solution did not work in my case. I had to update yarn to 1.x version that supports version resolutions (https://yarnpkg.com/en/docs/selective-version-resolutions) and then add to
package.json
```
  "resolutions": {
    "vue-loader/js-beautify": "~1.6.14"
  },
```

**Comment by pzdz** [comment]
It is fixed with the newest vue-loader release 13.0.5 (https://github.com/vuejs/vue-loader/commit/97bd432bba4350988bfd0db6d7a1a514b66a9826).
